[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-world"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = ["requests", "aws-lambda-powertools[tracer]"]

[tool.setuptools]
py-modules = ["app"]
